name: publish

on:
  push:
    branches: [master, main]
    tags-ignore: ['**']
  schedule: [cron: '0 0 * * 0'] # once in a week

env:
  CNAME: blog.iddqd.uk

jobs: # Docs: <https://help.github.com/en/articles/workflow-syntax-for-github-actions>
  build:
    name: Build the site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with: {hugo-version: 0.92.1, extended: true}

      - name: Build
        run: hugo --noChmod --noTimes --minify --environment production --baseURL "https://${CNAME}/" -d ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ${{ env.CNAME }}
